# Generated by Django 4.1.4 on 2022-12-15 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_question', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ananswer',
            options={'verbose_name': 'ответ', 'verbose_name_plural': 'ответы'},
        ),
        migrations.AlterModelOptions(
            name='grouptest',
            options={'verbose_name': 'набор', 'verbose_name_plural': 'наборы'},
        ),
        migrations.AlterModelOptions(
            name='nametest',
            options={'verbose_name': 'тест', 'verbose_name_plural': 'тесты'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'вопрос', 'verbose_name_plural': 'вопросы'},
        ),
    ]
