# Generated by Django 4.1.4 on 2022-12-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_question', '0002_alter_ananswer_options_alter_grouptest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouptest',
            name='description',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='описание'),
        ),
    ]
