# Generated by Django 4.1.4 on 2022-12-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_question', '0003_grouptest_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouptest',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
    ]
