# Generated by Django 4.1.4 on 2022-12-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_question', '0004_alter_grouptest_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ananswer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='название'),
        ),
    ]
